### ISSUE TITLE
Snap not working

### ISSUE THREAD

**Issue by soumyaDghosh** [Sjoerd1993/Graphs#322]
Okay.. so, this is like bolts from the blue. The latest release for the snap doesn't run. It throws this error:

```
Traceback (most recent call last):
  File "/snap/graphs/x1/usr/bin/graphs", line 68, in <module>
    sys.exit(main.main(args))
  File "/snap/graphs/x1/usr/lib/python3.10/dist-packages/graphs/main.py", line 200, in main
    app = GraphsApplication(args)
  File "/snap/graphs/x1/usr/lib/python3.10/dist-packages/graphs/main.py", line 45, in __init__
    self.preferences = Preferences()
  File "/snap/graphs/x1/usr/lib/python3.10/dist-packages/graphs/preferences.py", line 12, in __init__
    self.load()
  File "/snap/graphs/x1/usr/lib/python3.10/dist-packages/graphs/preferences.py", line 44, in load
    if set(item.keys()) != set(import_params_template[key].keys()):
AttributeError: 'str' object has no attribute 'keys'
```

As much the difference I checked between the snap and the flatpak files, is, it has the `fonttools` version to 4.40.0 which I tried to manually specify but, no luck as it's auto fetched from its `requirements.txt`. @Sjoerd1993 I can confirm that the version `1.5.3` that was in the edge channel worked perfectly. Kindly look into this.

EDIT: Rolled back the `1.6.0` update in snap.

**Comment by soumyaDghosh** [comment]
I guess this is the commit 13a50b90905ef159521b92a6b1d79792e6a10fb7 after which this error came up.

**Comment by soumyaDghosh** [comment]
This error is coming up if the old config file is still saved. I deleted the graphs `config` folder in `$HOME/snap` and this got fixed. Keeping this issue still open for a better resolution.

**Comment by cmkohnen** [comment]
The "breakage" was introduced in https://github.com/Sjoerd1993/Graphs/commit/4f0cf250f94660c1bf37ea0da39c6550d971f701. The change (or rather fix) was, that each attribute gets verified.
The error you're getting points to a string being where an actual dict should be. This was never the case (if I remember correctly).
So either you've got a bad config file for some reason or there is a bigger issue at hand. Will look into this tomorrow.

**Comment by Sjoerd1993** [comment]
Thanks for the report, will take a look at this

**Comment by Sjoerd1993** [comment]
I've tried a different ways to replicate this issue, including using config files from 1.5.2 and 1.5.3 in a freshly installed 1.6.0 installation, but I cannot seem to replicate this at all. It all works fine for me.

Everything seems to be pointing at a broken config file, but it would be nice to see what triggered this.

**Comment by soumyaDghosh** [comment]
It may be because, I enabled an option to have nightly builds from this repo, to be tested in the edge channel only. This channel is not meant for normal stable uers. So, I guess it has triggered my error. Thanks for looking into it though.

**Comment by cmkohnen** [comment]
I'm unable to reproduce this either. This issue is definitely related to the import file, else this wouldn't traceback to line 44. Looking at the commit history of [the template](https://github.com/Sjoerd1993/Graphs/commits/main/data/import.json), I see no way this could have happened automatically however.

**Comment by soumyaDghosh** [comment]
Thanks for the info. It most probably my fault then. Thanks for looking into it. My only intention was to check if the package is stable or not. Thanks again and sorry for the problem that I caused. Closing this.

**Comment by Sjoerd1993** [comment]
No problems, thanks for reporting this either way. It's better to be safe, than to ignore a potential breaking issue.
